#include "ADC.h"

int16_t result[SAMPLES_BUFFER];

void adcInitOneChannel(int pin)
{
  //Up to eight analog input channels CH[n ] (n=0..7) can be configured
    NRF_SAADC->ENABLE=(SAADC_ENABLE_ENABLE_Disabled<<SAADC_ENABLE_ENABLE_Pos);


    //CH[n].PSELP: input positive selection for CH[n]
    //CH[n].PSELN: input negative selection for CH[n]
    //CH[n].CONFIG: input configuration for CH[n]
    NRF_SAADC->CH[0].PSELP=(SAADC_CH_PSELP_PSELP_AnalogInput0<<SAADC_CH_PSELP_PSELP_Pos);     //AIN0->P002
    NRF_SAADC->CH[0].PSELN = (SAADC_CH_PSELN_PSELN_NC<<SAADC_CH_PSELN_PSELN_Pos);             //not connected
    NRF_SAADC->CH[0].CONFIG=(SAADC_CH_CONFIG_BURST_Disabled<<SAADC_CH_CONFIG_BURST_Pos)|      //burst disabled
                            (SAADC_CH_CONFIG_MODE_SE<<SAADC_CH_CONFIG_MODE_Pos)|              //single ended (pseln is ignored)
                            (SAADC_CH_CONFIG_TACQ_3us<<SAADC_CH_CONFIG_TACQ_Pos)|             //3us acquisition time
                            (SAADC_CH_CONFIG_REFSEL_Internal<<SAADC_CH_CONFIG_REFSEL_Pos)|    //internal reference (0.6V)
                            (SAADC_CH_CONFIG_GAIN_Gain1_6<<SAADC_CH_CONFIG_GAIN_Pos)|         //gain 1/6 
                            (SAADC_CH_CONFIG_RESP_Bypass<<SAADC_CH_CONFIG_RESP_Pos)|          //bypass resistor loader (negative channel resistor control)
                            (SAADC_CH_CONFIG_RESN_Bypass<<SAADC_CH_CONFIG_RESN_Pos);          //bypass resistor loader (positive channel resistor control)
    
    NRF_SAADC->RESOLUTION=(SAADC_RESOLUTION_VAL_14bit<<SAADC_RESOLUTION_VAL_Pos);   //14 bits resolution
    NRF_SAADC->OVERSAMPLE=(SAADC_OVERSAMPLE_OVERSAMPLE_Bypass<<SAADC_OVERSAMPLE_OVERSAMPLE_Pos);//Bypass oversample
    NRF_SAADC->SAMPLERATE=(SAADC_SAMPLERATE_MODE_Task<<SAADC_SAMPLERATE_MODE_Pos);//WITH TASK 
    NRF_SAADC->RESULT.MAXCNT=SAMPLES_BUFFER;
    NRF_SAADC->RESULT.PTR = (uint32_t)&result[0];
    NRF_SAADC->ENABLE=(SAADC_ENABLE_ENABLE_Enabled<<SAADC_ENABLE_ENABLE_Pos);


    NRF_SAADC->INTENCLR=0xFFFFFFFF;

    NRF_SAADC->EVENTS_STARTED = 0;
    NRF_SAADC->EVENTS_END = 0;
    NRF_SAADC->EVENTS_DONE = 0;
    NRF_SAADC->EVENTS_RESULTDONE = 0;
    NRF_SAADC->EVENTS_CALIBRATEDONE = 0;
    NRF_SAADC->EVENTS_STOPPED = 0;

    NRF_SAADC->TASKS_CALIBRATEOFFSET=1;
    while(NRF_SAADC->EVENTS_CALIBRATEDONE!=1){};
    NRF_SAADC->EVENTS_CALIBRATEDONE=0;

}

int readAnalog(int pin)
{
  NRF_SAADC->TASKS_START = 1;
  while(NRF_SAADC->EVENTS_STARTED == 0){};
  NRF_SAADC->EVENTS_STARTED = 0;

  NRF_SAADC->TASKS_SAMPLE = 1;
  while(NRF_SAADC->EVENTS_RESULTDONE!=1){};
  NRF_SAADC->EVENTS_RESULTDONE=0;
  return result[0];
}


////////////////ALL ADC INPUTS///////////////
void adcInitAll(void)
{

   //Note: Defines used in "NRF52840_BITS.h" file

   //Up to eight analog input channels CH[n ] (n=0..7) can be configured
    NRF_SAADC->ENABLE=(SAADC_ENABLE_ENABLE_Disabled<<SAADC_ENABLE_ENABLE_Pos);


    //CH[n].PSELP: input positive selection for CH[n]
    //CH[n].PSELN: input negative selection for CH[n]
    //CH[n].CONFIG: input configuration for CH[n]
    NRF_SAADC->CH[0].PSELP=(SAADC_CH_PSELP_PSELP_AnalogInput0<<SAADC_CH_PSELP_PSELP_Pos);     //AIN0->P002
    NRF_SAADC->CH[0].PSELN = (SAADC_CH_PSELN_PSELN_NC<<SAADC_CH_PSELN_PSELN_Pos);             //not connected
    NRF_SAADC->CH[0].CONFIG=(SAADC_CH_CONFIG_BURST_Disabled<<SAADC_CH_CONFIG_BURST_Pos)|      //burst disabled
                            (SAADC_CH_CONFIG_MODE_SE<<SAADC_CH_CONFIG_MODE_Pos)|              //single ended (pseln is ignored)
                            (SAADC_CH_CONFIG_TACQ_3us<<SAADC_CH_CONFIG_TACQ_Pos)|             //3us acquisition time
                            (SAADC_CH_CONFIG_REFSEL_Internal<<SAADC_CH_CONFIG_REFSEL_Pos)|    //internal reference (0.6V)
                            (SAADC_CH_CONFIG_GAIN_Gain1_6<<SAADC_CH_CONFIG_GAIN_Pos)|         //gain 1/6 
                            (SAADC_CH_CONFIG_RESP_Bypass<<SAADC_CH_CONFIG_RESP_Pos)|          //bypass resistor loader (negative channel resistor control)
                            (SAADC_CH_CONFIG_RESN_Bypass<<SAADC_CH_CONFIG_RESN_Pos);          //bypass resistor loader (positive channel resistor control)
    
   


    NRF_SAADC->CH[1].PSELP=(SAADC_CH_PSELP_PSELP_AnalogInput1<<SAADC_CH_PSELP_PSELP_Pos);   // AIN1
    NRF_SAADC->CH[1].PSELN = (SAADC_CH_PSELN_PSELN_NC<<SAADC_CH_PSELN_PSELN_Pos);          //not connected
    NRF_SAADC->CH[1].CONFIG=(SAADC_CH_CONFIG_BURST_Disabled<<SAADC_CH_CONFIG_BURST_Pos)|(SAADC_CH_CONFIG_MODE_SE<<SAADC_CH_CONFIG_MODE_Pos)|(SAADC_CH_CONFIG_TACQ_3us<<SAADC_CH_CONFIG_TACQ_Pos)|(SAADC_CH_CONFIG_REFSEL_Internal<<SAADC_CH_CONFIG_REFSEL_Pos)|(SAADC_CH_CONFIG_GAIN_Gain1_6<<SAADC_CH_CONFIG_GAIN_Pos)|(SAADC_CH_CONFIG_RESP_Bypass<<SAADC_CH_CONFIG_RESP_Pos)|(SAADC_CH_CONFIG_RESN_Bypass<<SAADC_CH_CONFIG_RESN_Pos);//BURTS OFF|MODE SINGLE|3US|REF=0,6V|
    
    NRF_SAADC->CH[2].PSELP=(SAADC_CH_PSELP_PSELP_AnalogInput2<<SAADC_CH_PSELP_PSELP_Pos);   //AIN2
    NRF_SAADC->CH[2].PSELN = (SAADC_CH_PSELN_PSELN_NC<<SAADC_CH_PSELN_PSELN_Pos);            //not connected
    NRF_SAADC->CH[2].CONFIG=(SAADC_CH_CONFIG_BURST_Disabled<<SAADC_CH_CONFIG_BURST_Pos)|(SAADC_CH_CONFIG_MODE_SE<<SAADC_CH_CONFIG_MODE_Pos)|(SAADC_CH_CONFIG_TACQ_3us<<SAADC_CH_CONFIG_TACQ_Pos)|(SAADC_CH_CONFIG_REFSEL_Internal<<SAADC_CH_CONFIG_REFSEL_Pos)|(SAADC_CH_CONFIG_GAIN_Gain1_6<<SAADC_CH_CONFIG_GAIN_Pos)|(SAADC_CH_CONFIG_RESP_Bypass<<SAADC_CH_CONFIG_RESP_Pos)|(SAADC_CH_CONFIG_RESN_Bypass<<SAADC_CH_CONFIG_RESN_Pos);//BURTS OFF|MODE SINGLE|3US|REF=0,6V|
    
    NRF_SAADC->CH[3].PSELP=(SAADC_CH_PSELP_PSELP_AnalogInput3<<SAADC_CH_PSELP_PSELP_Pos);   //AIN3->P002
    NRF_SAADC->CH[3].PSELN = (SAADC_CH_PSELN_PSELN_NC<<SAADC_CH_PSELN_PSELN_Pos);            //not connected
    NRF_SAADC->CH[3].CONFIG=(SAADC_CH_CONFIG_BURST_Disabled<<SAADC_CH_CONFIG_BURST_Pos)|(SAADC_CH_CONFIG_MODE_SE<<SAADC_CH_CONFIG_MODE_Pos)|(SAADC_CH_CONFIG_TACQ_3us<<SAADC_CH_CONFIG_TACQ_Pos)|(SAADC_CH_CONFIG_REFSEL_Internal<<SAADC_CH_CONFIG_REFSEL_Pos)|(SAADC_CH_CONFIG_GAIN_Gain1_6<<SAADC_CH_CONFIG_GAIN_Pos)|(SAADC_CH_CONFIG_RESP_Bypass<<SAADC_CH_CONFIG_RESP_Pos)|(SAADC_CH_CONFIG_RESN_Bypass<<SAADC_CH_CONFIG_RESN_Pos);//BURTS OFF|MODE SINGLE|3US|REF=0,6V|

    NRF_SAADC->CH[4].PSELP=(SAADC_CH_PSELP_PSELP_AnalogInput4<<SAADC_CH_PSELP_PSELP_Pos);      //AIN4
    NRF_SAADC->CH[4].PSELN = (SAADC_CH_PSELN_PSELN_NC<<SAADC_CH_PSELN_PSELN_Pos);              //not connected
    NRF_SAADC->CH[4].CONFIG=(SAADC_CH_CONFIG_BURST_Disabled<<SAADC_CH_CONFIG_BURST_Pos)|(SAADC_CH_CONFIG_MODE_SE<<SAADC_CH_CONFIG_MODE_Pos)|(SAADC_CH_CONFIG_TACQ_3us<<SAADC_CH_CONFIG_TACQ_Pos)|(SAADC_CH_CONFIG_REFSEL_Internal<<SAADC_CH_CONFIG_REFSEL_Pos)|(SAADC_CH_CONFIG_GAIN_Gain1_6<<SAADC_CH_CONFIG_GAIN_Pos)|(SAADC_CH_CONFIG_RESP_Bypass<<SAADC_CH_CONFIG_RESP_Pos)|(SAADC_CH_CONFIG_RESN_Bypass<<SAADC_CH_CONFIG_RESN_Pos);//BURTS OFF|MODE SINGLE|3US|REF=0,6V|
    
    NRF_SAADC->CH[5].PSELP=(SAADC_CH_PSELP_PSELP_AnalogInput5<<SAADC_CH_PSELP_PSELP_Pos);     //AIN5->P0
    NRF_SAADC->CH[5].PSELN = (SAADC_CH_PSELN_PSELN_NC<<SAADC_CH_PSELN_PSELN_Pos);              //not connected
    NRF_SAADC->CH[5].CONFIG=(SAADC_CH_CONFIG_BURST_Disabled<<SAADC_CH_CONFIG_BURST_Pos)|(SAADC_CH_CONFIG_MODE_SE<<SAADC_CH_CONFIG_MODE_Pos)|(SAADC_CH_CONFIG_TACQ_3us<<SAADC_CH_CONFIG_TACQ_Pos)|(SAADC_CH_CONFIG_REFSEL_Internal<<SAADC_CH_CONFIG_REFSEL_Pos)|(SAADC_CH_CONFIG_GAIN_Gain1_6<<SAADC_CH_CONFIG_GAIN_Pos)|(SAADC_CH_CONFIG_RESP_Bypass<<SAADC_CH_CONFIG_RESP_Pos)|(SAADC_CH_CONFIG_RESN_Bypass<<SAADC_CH_CONFIG_RESN_Pos);//BURTS OFF|MODE SINGLE|3US|REF=0,6V|

    NRF_SAADC->CH[6].PSELP=(SAADC_CH_PSELP_PSELP_AnalogInput6<<SAADC_CH_PSELP_PSELP_Pos);     //AIN6
    NRF_SAADC->CH[6].PSELN = (SAADC_CH_PSELN_PSELN_NC<<SAADC_CH_PSELN_PSELN_Pos);              //not connected
    NRF_SAADC->CH[6].CONFIG=(SAADC_CH_CONFIG_BURST_Disabled<<SAADC_CH_CONFIG_BURST_Pos)|(SAADC_CH_CONFIG_MODE_SE<<SAADC_CH_CONFIG_MODE_Pos)|(SAADC_CH_CONFIG_TACQ_3us<<SAADC_CH_CONFIG_TACQ_Pos)|(SAADC_CH_CONFIG_REFSEL_Internal<<SAADC_CH_CONFIG_REFSEL_Pos)|(SAADC_CH_CONFIG_GAIN_Gain1_6<<SAADC_CH_CONFIG_GAIN_Pos)|(SAADC_CH_CONFIG_RESP_Bypass<<SAADC_CH_CONFIG_RESP_Pos)|(SAADC_CH_CONFIG_RESN_Bypass<<SAADC_CH_CONFIG_RESN_Pos);//BURTS OFF|MODE SINGLE|3US|REF=0,6V|
    
    NRF_SAADC->CH[7].PSELP=(SAADC_CH_PSELP_PSELP_AnalogInput7<<SAADC_CH_PSELP_PSELP_Pos);   //AIN7->P0.31
    NRF_SAADC->CH[7].PSELN = (SAADC_CH_PSELN_PSELN_NC<<SAADC_CH_PSELN_PSELN_Pos);            //not connected
    NRF_SAADC->CH[7].CONFIG=(SAADC_CH_CONFIG_BURST_Disabled<<SAADC_CH_CONFIG_BURST_Pos)|(SAADC_CH_CONFIG_MODE_SE<<SAADC_CH_CONFIG_MODE_Pos)|(SAADC_CH_CONFIG_TACQ_3us<<SAADC_CH_CONFIG_TACQ_Pos)|(SAADC_CH_CONFIG_REFSEL_Internal<<SAADC_CH_CONFIG_REFSEL_Pos)|(SAADC_CH_CONFIG_GAIN_Gain1_6<<SAADC_CH_CONFIG_GAIN_Pos)|(SAADC_CH_CONFIG_RESP_Bypass<<SAADC_CH_CONFIG_RESP_Pos)|(SAADC_CH_CONFIG_RESN_Bypass<<SAADC_CH_CONFIG_RESN_Pos);//BURTS OFF|MODE SINGLE|3US|REF=0,6V|
    


    NRF_SAADC->RESOLUTION=(SAADC_RESOLUTION_VAL_14bit<<SAADC_RESOLUTION_VAL_Pos);   //14 bits resolution
    NRF_SAADC->OVERSAMPLE=(SAADC_OVERSAMPLE_OVERSAMPLE_Bypass<<SAADC_OVERSAMPLE_OVERSAMPLE_Pos);//Bypass oversample
    NRF_SAADC->SAMPLERATE=(SAADC_SAMPLERATE_MODE_Task<<SAADC_SAMPLERATE_MODE_Pos);//WITH TASK 
    NRF_SAADC->RESULT.MAXCNT=SAMPLES_BUFFER;
    NRF_SAADC->RESULT.PTR = (uint32_t)&result[0];
    NRF_SAADC->ENABLE=(SAADC_ENABLE_ENABLE_Enabled<<SAADC_ENABLE_ENABLE_Pos);


    NRF_SAADC->INTENCLR=0xFFFFFFFF;

    NRF_SAADC->EVENTS_STARTED = 0;
    NRF_SAADC->EVENTS_END = 0;
    NRF_SAADC->EVENTS_DONE = 0;
    NRF_SAADC->EVENTS_RESULTDONE = 0;
    NRF_SAADC->EVENTS_CALIBRATEDONE = 0;
    NRF_SAADC->EVENTS_STOPPED = 0;

    NRF_SAADC->TASKS_CALIBRATEOFFSET=1;
    while(NRF_SAADC->EVENTS_CALIBRATEDONE!=1){};
    NRF_SAADC->EVENTS_CALIBRATEDONE=0;
}

int readAnalogs(int pin)
{

  NRF_SAADC->TASKS_START = 1;
  while(NRF_SAADC->EVENTS_STARTED == 0){};
  NRF_SAADC->EVENTS_STARTED = 0;

  NRF_SAADC->TASKS_SAMPLE = 1;
  while(NRF_SAADC->EVENTS_RESULTDONE!=1){};
  NRF_SAADC->EVENTS_RESULTDONE=0;
  while(NRF_SAADC->EVENTS_END == 0){};
  NRF_SAADC->EVENTS_END = 0;
  return result[pin];



}

