#include "spi.h"


uint8_t spi_send(char data){
    char rx=0;

    NRF_SPIM0->RXD.MAXCNT=1;
    NRF_SPIM0->RXD.PTR=(uint32_t)&rx;
    
    NRF_SPIM0->TXD.MAXCNT=sizeof(data);
    NRF_SPIM0->TXD.PTR=(uint32_t)&data;

    NRF_SPIM0->TASKS_START=1;
    while(NRF_SPIM0->EVENTS_STARTED==0){};
    NRF_SPIM0->EVENTS_STARTED=0;
     NRF_P1->OUT=(0<<12);
    while(NRF_SPIM0->EVENTS_ENDTX==0){};
    NRF_SPIM0->EVENTS_ENDTX=0;
    while(NRF_SPIM0->EVENTS_ENDRX==0){};
    NRF_SPIM0->EVENTS_ENDRX=0;
    while(NRF_SPIM0->EVENTS_END==0){};
    NRF_SPIM0->EVENTS_END=0;
    NRF_P1->OUT=(1<<12);

    return rx;
}

void spi_init(void){

  NRF_SPIM0->ENABLE=SPIM_ENABLE_ENABLE_Disabled<<SPIM_ENABLE_ENABLE_Pos;
  
  NRF_P1->PIN_CNF[12]=GPIO_PIN_CNF_DIR_Output<<GPIO_PIN_CNF_DIR_Pos;//CS
  NRF_P1->OUT=(0<<12);
  NRF_P1->PIN_CNF[15]=GPIO_PIN_CNF_DIR_Output<<GPIO_PIN_CNF_DIR_Pos;//CLK
  NRF_P1->OUT=(0<<15);
  NRF_P1->PIN_CNF[14]=(GPIO_PIN_CNF_DIR_Input<<GPIO_PIN_CNF_DIR_Pos)|(GPIO_PIN_CNF_PULL_Disabled<<GPIO_PIN_CNF_PULL_Pos);//MISO
  NRF_P1->PIN_CNF[13]=GPIO_PIN_CNF_DIR_Output<<GPIO_PIN_CNF_DIR_Pos;//MOSI
  NRF_P1->OUT=(0<<13);

  NRF_SPIM0->PSEL.CSN =  0x7FFFFFEC;//P1.12
  NRF_SPIM0->PSEL.MOSI = 0x7FFFFFED;//P1.13
  NRF_SPIM0->PSEL.MISO = 0x7FFFFFEE;//P1.14
  NRF_SPIM0->PSEL.SCK =  0x7FFFFFEF;//P1.15
  
  NRF_SPIM0->FREQUENCY=SPIM_FREQUENCY_FREQUENCY_M1<<SPIM_FREQUENCY_FREQUENCY_Pos;

  NRF_SPIM0->CONFIG= (SPIM_CONFIG_CPHA_Leading<<SPIM_CONFIG_CPHA_Pos) //MODE 0 MSBFIRST
                    |(SPIM_CONFIG_CPOL_ActiveHigh<<SPIM_CONFIG_CPOL_Pos)
                    |(SPIM_CONFIG_ORDER_MsbFirst<<SPIM_CONFIG_ORDER_Pos);

  NRF_SPIM0->CSNPOL=SPIM_CSNPOL_CSNPOL_LOW<<SPIM_CSNPOL_CSNPOL_Pos; //CS Standard state LOW

  NRF_SPIM0->ENABLE=SPIM_ENABLE_ENABLE_Enabled<<SPIM_ENABLE_ENABLE_Pos;

}